version: "3.8"

services:

  db:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_DB: proyectofinal
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - grpc-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "proyectofinal", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s
      
  grpc-server:
    build: 
      context: .
      dockerfile: server/Dockerfile.server
    ports:
      - "50051:50051"
    depends_on:
      - db
    networks:
      - grpc-network

  grpc-client:
    build: 
      context: .
      dockerfile: client/Dockerfile.client
    depends_on:
      - grpc-server
      - db
    networks:
      - grpc-network

  grpc-producer:
    build: 
      context: .
      dockerfile: producer/Dockerfile.producer
    ports:
      - "5000:5000"
    depends_on:
      - grpc-server
    networks:
      - grpc-network

networks:
  grpc-network:
    driver: bridge

volumes:
  postgres_data: {}
