# Usa una imagen base de Python
FROM python:3.12

# Define el directorio de trabajo
WORKDIR /app

# Copia los archivos de la aplicación
COPY ./Task_6/client/ .

# Instala las dependencias
RUN pip install --no-cache-dir -r requirements.txt


# Ejecuta el servidor gRPC
CMD ["python", "clientmicro.py"]
