services:
  graphql:
    build: .
    container_name: graphql_server
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - JWT_SECRET=mi_super_secreto
      - REST_SERVICE_URL=http://host.docker.internal:8080/kafka/send
      - GRPC_SERVICE_HOST=grpc-server:50051

volumes:
  db-data:
