# Usa una imagen base de Python
FROM python:3.12

# Define el directorio de trabajo
WORKDIR /app

# Copia los archivos de la aplicación
COPY ./server/ .

# Instala las dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Expone el puerto para el servidor gRPC
EXPOSE 50051

# Ejecuta el servidor gRPC
CMD ["python", "server.py"]
