version: "3.8"

services:
  graphql:
    build: .
    container_name: graphql_server
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - JWT_SECRET=mi_super_secreto
      - REST_SERVICE_URL=http://rest-service:5000/api/data
      - GRPC_SERVICE_HOST=grpc-service:50051
    depends_on:
      - rest-service
      - grpc-service
      - db

  rest-service:
    image: node:20
    container_name: rest_service
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    command: ["node", "restServer.js"]

  grpc-service:
    image: node:20
    container_name: grpc_service
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "50051:50051"
    command: ["node", "grpcServer.js"]

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: estudiantes
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
